<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <title><?php echo $_SERVER['HTTP_HOST']?></title>
</head>
<body>
<div style="border: 2px solid #666;color:#000;padding:15px;">
  <h1>Oopps!</h1>
  <h3>We can't seem to find the page you're looking for.</h3>
  <p>Error Code: 404<br />
  Page Not Found. Please Visit Similar link which is given below</p>
</div>
    <br />
<h2><?php echo $this->message ?></h2>

  <?php if (isset($this->exception)): ?>
  
  <h3>Exception information:</h3>
  <p>
      <b>Message:</b> <?php echo $this->exception->getMessage() ?>
  </p>

  <h3>Stack trace:</h3>
  <pre><?php echo $this->exception->getTraceAsString() ?>
  </pre>

  <h3>Request Parameters:</h3>
  <pre><?php echo $this->escape(var_export($this->request->getParams(), true)) ?>
  </pre>

  <?php endif ?>
  
  <?php echo getMainBodyCategoryWisePostOnDetailPage('Main Body On Page',"Don't Miss")?> 
  <?php echo getMainBodyCategoryWisePostOnDetailPage('Main Body On Page','Lifestyle')?>
  <?php echo getMainBodyCategoryWisePostOnDetailPage('Main Body On Page','Sports')?>
  <?php echo getMainBodyCategoryWisePostOnDetailPage('Main Body On Page','Bollywood')?>

</body>
</html>
