<?php

$_SESSION['timeout'] = 60;

//admin session object create

$adminsession=new Zend_Session_Namespace('admin');

$obj = new Default_Model_DbTable_User();

$recods = $obj->getAdminByUser($adminsession->username);

//$city = $recods['city'];

//$user_id = $recods['user_id'];
//$usertype = $recods['user_type'];

?>

	<!-- DATE PICKER -->

    <!--<link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">-->

	<!--<script src="//code.jquery.com/jquery-1.10.2.js"></script>-->

    <script src="<?php echo $this->baseUrl();?>/public/datepicker/jquery-ui.js"></script>

    <script src="<?php echo $this->baseUrl();?>/public/datepicker/jquery.timepicker.js"></script>

    <link href="<?php echo $this->baseUrl();?>/public/datepicker/jquery.timepicker.css" rel="stylesheet" />

    <script>

	$(function() {

    	$( "#astrodate" ).datepicker({ 

			minDate: -0, 

			maxDate: "+10D", 

			dateFormat: 'yy-m-d'

         });

  	

		//$('#astrodate').timepicker();

    });

    </script>

    <!-- / DATE PICKER -->
<?php
if(!empty($_POST['aries'])){
$aries=$_POST['aries'];	
}else{
$aries=$this->data['aries'];
}
if(!empty($_POST['taurus'])){
$taurus=$_POST['taurus'];	
}else{
$taurus=$this->data['taurus'];
}
if(!empty($_POST['gemini'])){
$gemini=$_POST['gemini'];	
}else{
$gemini=$this->data['gemini'];
}
if(!empty($_POST['cancer'])){
$cancer	=$_POST['cancer'];	
}else{
$cancer=$this->data['cancer'];
}
if(!empty($_POST['leo'])){
$leo=$_POST['leo'];	
}else{
$leo=$this->data['leo'];
}
if(!empty($_POST['virgo'])){
$virgo=$_POST['virgo'];	
}else{
$virgo=$this->data['virgo'];
}
if(!empty($_POST['libra'])){
$libra=$_POST['libra'];	
}else{
$libra=$this->data['libra'];
}
if(!empty($_POST['scorpio'])){
$scorpio=$_POST['scorpio'];	
}else{
$scorpio=$this->data['scorpio'];
}
if(!empty($_POST['sagittarius'])){
$sagittarius=$_POST['sagittarius'];	
}else{
$sagittarius=$this->data['sagittarius'];
}
if(!empty($_POST['capricorn'])){
$capricorn=$_POST['capricorn'];	
}else{
$capricorn=$this->data['capricorn'];
}
if(!empty($_POST['aquarius'])){
$aquarius=$_POST['aquarius'];	
}else{
$aquarius=$this->data['aquarius'];
}
if(!empty($_POST['pisces'])){
$pisces=$_POST['pisces'];	
}else{
$pisces=$this->data['pisces'];
}
if(!empty($_POST['astrodate'])){
$astrodate=$_POST['astrodate'];	
}else{
$astrodate=$this->data['astrodate'];
}
?>
<div class="pageheader">

      <h2><i class="fa fa-home"></i>Add Astrology</h2>

      <div class="breadcrumb-wrapper">

    

        <ol class="breadcrumb">

         

          <li><a href="<?php echo $this->baseUrl();?>/admin/astrology/"><strong>Back</strong></a></li>

        </ol>

      </div>

    </div>

    

    <div class="contentpanel">

      

      <div class="panel panel-default">

      

        <div class="panel-body panel-body-nopadding">

          
	<div class="error_container"><span class="error"><?php if(!empty($this->error['recordExist'])){ echo $this->error['recordExist'];}?></span></div>
    
    <form name="frmpost" id="frmpost" enctype="multipart/form-data" method="post" action="<?php echo $this->baseUrl();?>/admin/astrology/edit/id/<?php echo $this->data['idastrology'];?>">
			<div class="form-group">

              <label class="col-sm-2 control-label">मेस राशी</label>

              <div class="col-sm-10">

                <input type="text" placeholder="Enter मेस राशी" id="aries" name="aries" value="<?= $aries ?>" class="form-control" maxlength="250" />
				<div class="error_container"><span class="error"><?php if(!empty($this->error['aries'])){ echo $this->error['aries'];}?></span></div>
              </div>

            </div>
            <div class="form-group">

              <label class="col-sm-2 control-label">वृषभ राशी</label>

              <div class="col-sm-10">

                <input type="text" placeholder="Enter वृषभ राशी" id="taurus" name="taurus" value="<?= $taurus ?>" class="form-control" maxlength="250" />
				<div class="error_container"><span class="error"><?php if(!empty($this->error['taurus'])){ echo $this->error['taurus'];}?></span></div>
              </div>

            </div>
            <div class="form-group">

              <label class="col-sm-2 control-label">मिथुन राशी</label>

              <div class="col-sm-10">

                <input type="text" placeholder="Enter मिथुन राशी" id="gemini" name="gemini" value="<?= $gemini ?>" class="form-control" maxlength="250" />
				<div class="error_container"><span class="error"><?php if(!empty($this->error['gemini'])){ echo $this->error['gemini'];}?></span></div>
              </div>

            </div>
            <div class="form-group">

              <label class="col-sm-2 control-label">कर्क राशी</label>

              <div class="col-sm-10">

                <input type="text" placeholder="Enter कर्क राशी" id="cancer" name="cancer" value="<?= $cancer ?>" class="form-control" maxlength="250" />
				<div class="error_container"><span class="error"><?php if(!empty($this->error['cancer'])){ echo $this->error['cancer'];}?></span></div>
              </div>

            </div>
            <div class="form-group">

              <label class="col-sm-2 control-label">सिंह राशी</label>

              <div class="col-sm-10">

                <input type="text" placeholder="Enter सिंह राशी" id="leo" name="leo" value="<?= $leo ?>" class="form-control" maxlength="250" />
				<div class="error_container"><span class="error"><?php if(!empty($this->error['leo'])){ echo $this->error['leo'];}?></span></div>
              </div>

            </div>
            <div class="form-group">

              <label class="col-sm-2 control-label">कन्या राशी</label>

              <div class="col-sm-10">

                <input type="text" placeholder="Enter कन्या राशी" id="virgo" name="virgo" value="<?= $virgo ?>" class="form-control" maxlength="250" />
				<div class="error_container"><span class="error"><?php if(!empty($this->error['virgo'])){ echo $this->error['virgo'];}?></span></div>
              </div>

            </div>
            <div class="form-group">

              <label class="col-sm-2 control-label">तुला राशी</label>

              <div class="col-sm-10">

                <input type="text" placeholder="Enter तुला राशी" id="libra" name="libra" value="<?= $libra ?>" class="form-control" maxlength="250" />
				<div class="error_container"><span class="error"><?php if(!empty($this->error['libra'])){ echo $this->error['libra'];}?></span></div>
              </div>

            </div>
            <div class="form-group">

              <label class="col-sm-2 control-label">वृश्चिक राशी</label>

              <div class="col-sm-10">

                <input type="text" placeholder="Enter वृश्चिक राशी" id="scorpio" name="scorpio" value="<?= $scorpio ?>" class="form-control" maxlength="250" />
				<div class="error_container"><span class="error"><?php if(!empty($this->error['scorpio'])){ echo $this->error['scorpio'];}?></span></div>
              </div>

            </div>
            <div class="form-group">

              <label class="col-sm-2 control-label">धनु राशी</label>

              <div class="col-sm-10">

                <input type="text" placeholder="Enter धनु राशी" id="sagittarius" name="sagittarius" value="<?= $sagittarius ?>" class="form-control" maxlength="250" />
				<div class="error_container"><span class="error"><?php if(!empty($this->error['sagittarius'])){ echo $this->error['sagittarius'];}?></span></div>
              </div>

            </div>
            <div class="form-group">

              <label class="col-sm-2 control-label">मकर राशी</label>

              <div class="col-sm-10">

                <input type="text" placeholder="Enter मकर राशी" id="capricorn" name="capricorn" value="<?= $capricorn ?>" class="form-control" maxlength="250" />
				<div class="error_container"><span class="error"><?php if(!empty($this->error['capricorn'])){ echo $this->error['capricorn'];}?></span></div>
              </div>

            </div>
            <div class="form-group">

              <label class="col-sm-2 control-label">कुंभ राशी</label>

              <div class="col-sm-10">

                <input type="text" placeholder="Enter कुंभ राशी" id="aquarius" name="aquarius" value="<?= $aquarius ?>" class="form-control" maxlength="250" />
				<div class="error_container"><span class="error"><?php if(!empty($this->error['aquarius'])){ echo $this->error['aquarius'];}?></span></div>
              </div>

            </div>
            <div class="form-group">

              <label class="col-sm-2 control-label">मीन राशी</label>

              <div class="col-sm-10">

                <input type="text" placeholder="Enter मीन राशी" id="pisces" name="pisces"  value="<?= $pisces ?>" class="form-control" maxlength="250" />
				<div class="error_container"><span class="error"><?php if(!empty($this->error['pisces'])){ echo $this->error['pisces'];}?></span></div>
              </div>

            </div>
            
                <div class="form-group">
    
                    <label class="col-sm-2 control-label">Date</label>
    
                    <div class="col-sm-1" style="margin-right:5px;">
    
                       <small>Date</small> <input class="form-control" id="astrodate" name="astrodate" value="<?= $astrodate ?>" type="text" maxlength="10" style="width:90px;" autocomplete="off" />
    					<div class="error_container"><span class="error"><?php if(!empty($this->error['astrodate'])){ echo $this->error['astrodate'];}?></span></div>
                    </div>
                </div>
			
            

        

        <div class="panel-footer">

			 <div class="row">

				<div class="col-sm-6 col-sm-offset-3">

				  <button class="btn btn-primary">Update</button>&nbsp;
				  <button class="btn btn-default">Cancel</button>

				</div>

			 </div>

		  </div><!-- panel-footer -->

        </form>

      </div><!-- panel -->

      