<?php
$_SESSION['timeout'] = 60;
		
include_once('public/fckeditor/fckeditor.php');
$city = $this->data['city'];
$postid = $this->data['post_id'];

$sql = "SELECT * FROM `post_category` WHERE `post_id` = '$postid'";
//echo $sql;die(); 
$res = Zend_Registry::get("db")->fetchAll($sql);

$objMeta = new Default_Model_DbTable_Category();
//$adminMetaVals = $objMeta->getMetaKeyVal($pid);
$category = $objMeta->getMetaKeyVal($postid);
$special = explode(',',$category);
//print_r($special);die();

$adminsession=new Zend_Session_Namespace('admin');
$obj = new Default_Model_DbTable_User();

$recods = $obj->getAdminByUser($adminsession->username);
$city = $recods['city'];
$usertype = $recods['user_type'];

function selectedCatgories($post_id, $category_id){
	if ($post_id != ''){
		$category_name = '';
		$sql = "";
		$sql = "SELECT category_name FROM `post_category` WHERE `post_id` = '".$post_id."' AND category_id = '".$category_id."'";
		//echo $sql; 
		$rsCat = Zend_Registry::get("db")->fetchAll($sql);	
		if($rsCat){ foreach($rsCat as $resCat){
			$category_name = $resCat['category_name'];
		}}
		return $category_name;
	}
}
?>

	<script type="text/javascript">
	$(document).ready(function() {
			$("#city").change(function() {
			//alert($(this).val());
			url = '<?php echo $this->baseUrl();?>/admin/post/ajaxcall?city='+$(this).val();
			//alert(url);
			$.get(url, function(data) {
				$("#location_id").html(data);
			});
		});

	});
	function getPrakhand(location_Id) {
		//$("#city").val();
		//alert('location_Id = ' + location_Id);
		//alert('pid = ' + $('#pid').val());
		//$('#location_id1').hide();
			
		url = '<?php echo $this->baseUrl();?>/admin/post/ajaxcall?city='+$("#city").val()+'&pid='+$("#pid").val()+'&location_Id='+location_Id;
		//alert(url);
		$.get(url, function(data) {
			//$("#spnBlock").html(data);
			$("#location_id").html(data);
		});
	}
	</script>

	<!-- DATE PICKER -->
    <!--<link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">-->
	<!--<script src="//code.jquery.com/jquery-1.10.2.js"></script>-->
    <script src="<?php echo $this->baseUrl();?>/public/datepicker/jquery-ui.js"></script>
    <script src="<?php echo $this->baseUrl();?>/public/datepicker/jquery.timepicker.js"></script>
    <link href="<?php echo $this->baseUrl();?>/public/datepicker/jquery.timepicker.css" rel="stylesheet" />
    <script>
	$(function() {
    	$( "#scheduleDate" ).datepicker({ 
			minDate: -0, 
			maxDate: "+10D", 
			dateFormat: 'yy-m-d'
         });
  	
		$('#scheduleTime').timepicker();
    });
    </script>
    <!-- / DATE PICKER -->

	<!-- / PHOTO PREVIEW -->
    <script type="text/javascript">//<![CDATA[ 
        $(window).load(function () {
            function readPhotoURL(input) {
                //alert(input.files[0].size);
                if (input.files[0].size > 2097152) {
                    alert('Please photo image size maximum 2mb only');
                    $("#image").val('');
					//$('#imgPhoto').hide();
                    return (false);
                }
                if (input.files && input.files[0]) {
                    var reader = new FileReader();
                    $('#image').show();
                    reader.onload = function (e) {
						$('#imgPhoto').show();
                        $('#imgPhoto').attr('src', e.target.result);
                    }
                    reader.readAsDataURL(input.files[0]);
                }
            }

            $("#image").change(function () {
                var imgName = $("#image").val();
                var sptImgName;
                var extImageName;
                if ($.browser.mozilla == false) {
                    sptImgName = imgName.split("\\");
                    extImageName = sptImgName[2].split('.');

                } else {
                    sptImgName = imgName;
                    extImageName = sptImgName.split('.');
                }

                var getExt = extImageName[1];
                if (getExt != 'jpg' && getExt != 'jpeg') {
                    alert('Please upload JPG, JPEG file in Photo of the post.');
                    $('#image').val('');
					//$('#imgPhoto').hide();
                    return (false);
                } //else { //$('#imgPhoto').show(); }

                if ($.browser.chrome || $.browser.mozilla) {
                    readPhotoURL(this);
                } else if ($.browser.msie) {
                    $('#imgPhoto').show();
                    document.getElementById('imgPhoto').src = $("#txtphoto").val();
                }
            });
        });//]]>  
    </script>
    <!-- / PHOTO PREVIEW -->
<div class="pageheader">
    <h2><i class="fa fa-home"></i>Edit Post</h2>
    <div class="breadcrumb-wrapper">
    	<ol class="breadcrumb">
    		<li><a href="<?php echo $this->baseUrl();?>/admin/post/"><strong>Back</strong></a></li>
    	</ol>
    </div>
</div>
<form name="frmpost" id="frmpost" enctype="multipart/form-data" method="post" action="<?php echo $this->baseUrl();?>/admin/post/edit/id/<?php echo $this->data['post_id'];?>">
<div class="contentpanel">
	<div class="panel panel-default">
		<div class="panel-body panel-body-nopadding">
             <div class="form-group">
                <label class="col-sm-3 control-label">हेडलाइन</label>
                <div class="col-sm-9">
                    <input type="text" placeholder="Enter Headline" id="headline" name="headline" value="<?php echo $this->data['headline'];?>" class="form-control" maxlength="75"  />
					<div class="error_container"><span class="error"><?php if(!empty($this->error['headline'])){ echo $this->error['headline'];}?></span></div>
                </div>
            </div>
            <div class="form-group">
                <label class="col-sm-3 control-label">इंट्रो</label>
                <div class="col-sm-9">
                    <textarea class="form-control" id="intro" name="intro" rows="5" ><?php echo $this->data['intro'];?></textarea>
                </div>
				<div class="error_container"><span class="error"><?php if(!empty($this->error['intro'])){ echo $this->error['intro'];}?></span></div>
            </div>
            <div class="form-group">
                <label class="col-sm-3 control-label">कैटगरी</label>
                <div class="col-sm-9">
                    <?php 
                    $query = "SELECT * FROM `category` WHERE status = '1' ORDER BY category";
                    $res = Zend_Registry::get("db")->fetchAll($query);
                    ?>
                    <select class="select2" name="category[]" id="category" multiple="multiple"  size="6" required>
                        <!--<?php //if($res){ foreach($res as $val){
                            //$category = $objMeta->getMetaKeyVal($postid);
                            //$special = explode(',',$category);
                        ?>
                        <option value="<?php //echo $val['category'];?>" <?php //foreach($special as $value){ if($val['category'] == $value){echo " selected = selected";}}?>><?php //echo $val['category'];?></option>
                        <?php //}}?>-->
                        <?php
						if($res){ 
							foreach($res as $catVal)
							{ 
								if (selectedCatgories($postid, $catVal['category_id']) == $catVal['category']){
									echo '<option selected="selected" value="'.$catVal['category_id'].'">'.$catVal['category'].'</option>';
								} else {
									echo '<option value="'.$catVal['category_id'].'">'.$catVal['category'].'</option>';
								}
							}
						}
						?>
                    </select>
					<div class="error_container"><span class="error"><?php if(!empty($this->error['category'])){ echo $this->error['category'];}?></span></div>
                </div>
            </div>
			<?php
            if($usertype != 2){
            ?>
                <div class="form-group">
                    <label class="col-sm-3 control-label">Select City</label>
                    <div class="col-sm-5">
                        <?php 
                        $query = "SELECT DISTINCT CONCAT(UCASE(MID(city,1,1)),LCASE(MID(city,2))) AS city FROM `location`";
                        $res = Zend_Registry::get("db")->fetchAll($query);
                        ?>
                        <select class="select2" id="city" name="city" data-placeholder="Choose a City..." >
                            <option value=""></option>
                            <?php 
                            if($res)
                            { 
                                foreach($res as $val)
                                { 
                                    if( strtolower($this->data['city']) ==  strtolower($val['city'])){
                                        echo '<option selected value="'.$val['city'].'">'.$val['city'].'</option>';
                                    } else {
                                        echo '<option value="'.$val['city'].'">'.$val['city'].'</option>';
                                    }
                                }
                            }
                            ?>
                        </select>
						<div class="error_container"><span class="error"><?php if(!empty($this->error['city'])){ echo $this->error['city'];}?></span></div>
                    </div>
                </div> 
        		<?php $location_id = $this->data['location_id'];?>
                <div class="form-group">
                    <label class="col-sm-3 control-label">प्रखंड</label>
                    <div class="col-sm-5"><span id="spnBlock"></span>
                        <select name="location_id" class="select2" id="location_id">
                            <option value="<?php echo $this->data['location_id'];?>"><?php echo $this->data['block_name'];?></option> 
                        </select>
						<div class="error_container"><span class="error"><?php if(!empty($this->error['location_id'])){ echo $this->error['location_id'];}?></span></div>
                    </div>
                </div>   
            <?php }?>  
           	<?php
            if($usertype != 0 && $usertype != 1){
            ?> 
                <div class="form-group">
                    <label class="col-sm-3 control-label">शहर</label>
                    <div class="col-sm-6">
                        <input type="text" id="city" name="city" value="<?php echo $this->data['city'];?>" readonly="readonly" class="form-control" />
						<div class="error_container"><span class="error"><?php if(!empty($this->error['city'])){ echo $this->error['city'];}?></span></div>
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-sm-3 control-label">प्रखंड</label>
                    <div class="col-sm-5">
                        <?php 
                        $query = "SELECT location_id, CONCAT(UCASE(MID(block_name,1,1)),LCASE(MID(block_name,2))) AS block_name FROM `location` WHERE isDeleted = 0 AND status = 1 AND `city`= '$city'";
                        $res = Zend_Registry::get("db")->fetchAll($query);
                        ?>
                        <select class="select2" id="location_id" name="location_id" data-placeholder="Select a block" >
                            <option value=""></option>
                            <?php 
                            if($res)
                            { 
                                foreach($res as $val)
                                { 
                                    if( $this->data['location_id'] == $val['location_id']){
                                        echo '<option selected="selected" value="'.$val['location_id'].'">'.$val['block_name'].'</option>';
                                    } else {
                                        echo '<option value="'.$val['location_id'].'">'.$val['block_name'].'</option>';
                                    }
                                }
                            }
                            ?>
                        </select>
						<div class="error_container"><span class="error"><?php if(!empty($this->error['location_id'])){ echo $this->error['location_id'];}?></span></div>
                    </div>
                </div> 
            <?php }?>
            <div class="form-group">
                <label class="col-sm-3 control-label" for="disabledinput">फोटो लगाएं</label>
                <div class="col-sm-9">
                    <input type="hidden" name="imageOld" id="imageOld" value="<?php echo $this->data['image']; ?>" />
                    <input type="file" name="image" id="image" class="form-control"  />
                    <div style="color:#FF0000;">width:700px, Height:350px</div>
                    <span id="lblError2" style="color: red;"></span>
                    <?php if($this->data['thumb_image'] != "") { ?>
                    <!--<img src="<?php //echo $this->baseUrl().'/public/products/image/thumb/'.$this->data['thumb_image']; ?>" width="50" align="absmiddle" />--><?php //echo $this->data['thumbImagePath']; ?>
                    <!--<img id="imgPhoto" src="<?php //echo $this->baseUrl();?>/public/admin/images/Blank.png" style="display:none;height:100px;width:150px;">-->
                    <img id="imgPhoto" src="<?php //echo $this->data['thumbImagePath']; ?><?php echo $this->baseUrl().'/public/products/image/'.$this->data['thumb_image']; ?>" style="height:100px;" align="absmiddle" />
					<?php } ?>
					<div class="error_container"><span class="error"><?php if(!empty($this->error['image'])){ echo $this->error['image'];}?></span></div>
                </div>
            </div>
            <div class="form-group">
                <label class="col-sm-3 control-label">English URL</label>
                <div class="col-sm-9">
                    <input type="text" placeholder="Enter English URL" id="englishurl" name="englishurl" value="<?php echo $this->data['english_url'];?>" class="form-control" maxlength="62" required  />
					<div class="error_container"><span class="error"><?php if(!empty($this->error['englishurl'])){ echo $this->error['englishurl'];}?></span></div>
                </div>
            </div>
            <div class="form-group">
                <label class="col-sm-3 control-label">Content
                    <div style="padding:20px 0 0 0;font-weight:bold;color:#FF0000;">
                    Replacement Tag For Site:<br />
                    RUPEES  - ##RS## <br />
                    </div>
                    <div style="padding:20px 0 0 0;font-size:17px;color:#666;">
                        e.g. सरकार ने राजेन्द्र को बहादुरी पुरूस्कार में <i class="fa fa-rupee"></i>20000 इनाम में दिए|
                    </div>
                    <div style="color:#FF0000;margin-top:20px;">
                        <strong>Paste highlighted code "<u>YOUTUBE VIDEO EMBED URL</u>" in "<u>Source</u>" and change the your path "https://youtube.com/..."</strong><br />
                        <strong>e.g.:</strong> <small style="background-color:#F93; color:#000;padding:4px;">&lt;p&gt;&lt;iframe src="https://www.youtube.com/embed/MIAyW-y-CrU" frameborder="0" allowfullscreen="" style="width:669px; height:370px;"&gt;&lt;/iframe&gt;&lt;/p&gt;</small>
                    </div>
                </label>
              
                <div class="col-sm-9">
                    <?php
                    $oFCKeditor = new FCKeditor('content');
                    $oFCKeditor->BasePath = $this->baseUrl()."/public/fckeditor/";
                    $oFCKeditor->ToolbarSet = 'MyToolbar';
                	$oFCKeditor->Value = $this->data['content'];
                    $oFCKeditor->Create();
                    $oFCKeditor->Height = 900;
                    $oFCKeditor->Width = 700;
                    ?>
					<div class="error_container"><span class="error"><?php if(!empty($this->error['content'])){ echo $this->error['content'];}?></span></div>
                </div>
            </div>
            <div class="form-group">
                <label class="col-sm-3 control-label">Video URL
                <div style="color:#FF0000;">
                    Paste "<u>YOUTUBE / VIMEO</u>" Video IFRAME Embed URL only
                </div>
                </label>
                <div class="col-sm-9">
                    <input type="text" class="form-control" name="videoURL" id="videoURL" value="<?php echo $this->data['videourl'];?>" />
                </div>
            </div>
            <?php
            if($usertype != 2){
            ?>
                <div class="form-group">
                    <label class="col-sm-3 control-label">प्रीयॉरिटी</label>
                    <div class="col-sm-2">
                        <select class="select2" id="priority" name="priority">
                            <option value="">Select a priority</option>
                            <?php 
                            for ($i=1; $i<=5; $i++){
                                if( $this->data['priority'] == $i){
                                    echo '<option selected="selected" value="'.$i.'">'.$i.'</option>';
                                } else {
                                    echo '<option value="'.$i.'">'.$i.'</option>';
                                }
                            }
                            ?>                 
                        </select>
						<div class="error_container"><span class="error"><?php if(!empty($this->error['priority'])){ echo $this->error['priority'];}?></span></div>
                    </div>
                </div>
            <?php }?>  
            
			<?php
			if($usertype != 2){
			?>
                <div class="form-group">
                  <label class="col-sm-3 control-label">हेडलाइन टाइप</label>
                  <div class="col-sm-2">
                    <select name="postType" id="postType" class="select2">
                        <option value="">Select</option>
                        <option value="BREAKING" <?php if ($this->data['postType'] == 'BREAKING'){ echo 'selected';}?>>BREAKING</option>
                        <option value="EXCLUSIVE" <?php if ($this->data['postType'] == 'EXCLUSIVE'){ echo 'selected';}?>>EXCLUSIVE</option>
                        <option value="FLASH" <?php if ($this->data['postType'] == 'FLASH'){ echo 'selected';}?>>FLASH</option>
                        <option value="STING OPERATION" <?php if ($this->data['postType'] == 'STING OPERATION'){ echo 'selected';}?>>STING OPERATION</option>
                    </select>
                  </div>
                </div>
            <?php
			} else {
				echo '<input type="hidden" name="postType">';	
			}
			?>
			<?php
            if($usertype != 2){
            ?>
                <div class="form-group" style="display:none;">
                    <label class="col-sm-3 control-label">Meta Title</label>
                    <div class="col-sm-6">
                        <input type="text" placeholder="Enter Meta title" id="metatitle" name="metatitle" value="<?php echo $this->data['meta_title'];?>" class="form-control" maxlength="62"  />
                    </div>
                </div>
                <div class="form-group" style="display:none;">
                    <label class="col-sm-3 control-label">Meta Keyword</label>
                    <div class="col-sm-7">
                        <textarea class="form-control" id="metakeyword" name="metakeyword" rows="5" ><?php echo $this->data['meta_keyword'];?></textarea>
                    </div>
                </div>
                <div class="form-group" style="display:none;">
                    <label class="col-sm-3 control-label">Meta Description</label>
                    <div class="col-sm-7">
                        <textarea class="form-control" id="metadescription" name="metadescription" rows="5" ><?php echo $this->data['meta_desc'];?></textarea>
                    </div>
                </div>
            <?php }else{?>
            	<div class="form-group" style="display:none;">
                    <label class="col-sm-3 control-label">Meta Title</label>
                    <div class="col-sm-6">
                        <input type="hidden" id="metatitle" name="metatitle" />
                    	<input type="hidden" id="metakeyword" name="metakeyword" />
                    	<input type="hidden" id="metadescription" name="metadescription" />
                        <input type="hidden" id="priority" name="priority" />
                        <input type="hidden" id="scheduleDate" name="scheduleDate" />
                        <input type="hidden" id="scheduleTime" name="scheduleTime" />
                    </div>
                </div>
          	<?php
			}
			?>
            <div class="form-group">
                <label class="col-sm-3 control-label">Reporter</label>
                <div class="col-sm-3">
                    <?php 
                    $query = "SELECT user_id AS idReporter, CONCAT(first_name, ' ', last_name) AS reporterName FROM `user` WHERE user_type = 2";
                    $res = Zend_Registry::get("db")->fetchAll($query);
                    ?>
                        <select class="select2" id="idReporter" name="idReporter">
                        <option value="">Select</option>
                        <?php if($res){ foreach($res as $val){ 
								if( strtolower($this->data['idReporter']) ==  strtolower($val['idReporter'])){
									echo '<option selected value="'.$val['idReporter'].'">'.$val['reporterName'].'</option>';
								} else {
									echo '<option value="'.$val['idReporter'].'">'.$val['reporterName'].'</option>';
								}
						?>
                       <?php }}?>
                        </select>
                  </div>
            </div> 
             <?php
            if($usertype != 2){
            ?>
                <div class="form-group">
                    <label class="col-sm-3 control-label">Is Schedule?</label>
                    <div class="col-sm-1" style="margin-right:5px;">
                       <small>Date</small> <input class="form-control" id="scheduleDate" name="scheduleDate" type="text" value="<?php echo $this->data['scheduleDate']; ?>" maxlength="10" style="width:90px;" autocomplete="off" />
                    </div>
                    <div class="col-sm-7">
                       <small>Time</small> <input class="form-control time" id="scheduleTime" name="scheduleTime" type="text" value="<?php echo $this->data['scheduleTime']; ?>" style="width:90px;" />
                    </div>
                </div>
            <?php
			}
			?>
            <div class="form-group">
                <div class="col-sm-12" align="center">
                	<?php if ($this->data['idReporter'] == $this->data['user_id']){
                    	$userId_reprterId_Is_Same = "YES";
					} else {
						$userId_reprterId_Is_Same = "NO";
					}?>
                    <input type="hidden" name="userId_reprterId_Is_Same" id="userId_reprterId_Is_Same" value="<?php echo $userId_reprterId_Is_Same;?>" />                    
                    <input type="hidden" name="pid" id="pid" value="<?php echo $this->data['post_id'];?>" />
                    <button class="btn btn-primary" id="submit" onclick="return validate()">Update</button>
                    <button class="btn btn-default">Cancel</button>
                </div>
            </div>
		</div>
	</div>
</div>
</form>	
</div><!-- panel -->
		<script>
	  	function validate() {
			var category = $('#category').val();
			//var priority = $('#priority').val();
			var city = $('#city').val(); 
			var location_id = $('#location_id').val();
			var headline = $('#headline').val();
			var englishurl = $('#englishurl').val();
			var intro = $('#intro').val();
			var image = $('#image').val();
			var content = $('#content').val();
			var scheduleDate = $('#scheduleDate').val();
			var scheduleTime = $('#scheduleTime').val();
			//alert('scheduleTime = '+ scheduleTime);
			
			if($.trim(category) == '' && category == null){
				alert('कृपया एक कैटगरी चुनें|');
				$('#category').focus();
				return (false);
			}
			if($.trim(city) == '' && city == null){
				alert('कृपया कोई एक शहर चुनें|');
				$('#city').focus();
				return (false);
			}
			if($.trim(location_id) == '' && location_id == null){
				alert('कृपया कोई एक प्रखंड चुनें|');
				$('#location_id').focus();
				return (false);
			}
			if($.trim(headline) == '' && headline == null){
				alert('कृपया हेडलाइन भरें|');
				$('#headline').focus();
				return (false);
			}
			if($.trim(englishurl) == '' && englishurl == null){
				alert('कृपया एन्लिश यू आर एल (URL) भरें|');
				$('#englishurl').focus();
				return (false);
			}
			if($.trim(intro) == '' && intro == null){
				alert('कृपया इंट्रो भरें|');
				$('#intro').focus();
				return (false);
			}
			if($.trim(image) == '' && image == null){
				alert('कृपया फोटो लगाएं|');
				$('#image').focus();
				return (false);
			}
            if ($.trim(scheduleDate) != '' && $.trim(scheduleTime) == ''){
				alert('आप अपने पोस्ट का समय निश्चित करें|');
				$('#scheduleTime').focus();
				return (false);
			}
			if ($.trim(scheduleTime) != '' && $.trim(scheduleDate) == ''){
				alert('आप अपने पोस्ट का तारीख निश्चित करें|');
				$('#scheduleDate').focus();
				return (false);
			}
			//if($.trim(content) == '' && content == null){
			//	alert('कृपया कंटेंट भरें|');
			//	$('#content').focus();
			//	return (false);
			//}
		};
	  	</script> 
<script>
getPrakhand('<?php echo $location_id;?>');
</script>