<?php
$adminsession = new Zend_Session_Namespace('admin');
$obj = new Default_Model_DbTable_User();
$recods = $obj->getAdminByUser($adminsession->username);
$usertype = $recods['user_type'];
?>
<script type="text/javascript">
	function deletePost(post_id){
		var iAgree = confirm("You are sure want to delete?.")
		if (iAgree == true){
			document.location.href="<?php echo $this->baseUrl();?>/admin/astrology/delete/id/" + post_id;
			return(true);
		} else {
			return (false);
		}
	}
</script>
<!-- SHARE THIS -->
<!--<script type="text/javascript">var switchTo5x=true;</script>-->
<script type="text/javascript" src="http://w.sharethis.com/button/buttons.js"></script>
<script type="text/javascript">stLight.options({publisher: "9ee8c443-57cf-44ea-8e67-11693a461baf", doNotHash: false, doNotCopy: false, hashAddressBar: false});
</script>
<!-- / SHARE THIS -->

<!-- PAGINATION -->

<!-- / PAGINATION -->

<div class="pageheader">
	<h2><i class="fa fa-home"></i>Manage Astrology</h2>
	<div class="breadcrumb-wrapper">
		<ol class="breadcrumb">
			<li><a href="<?php echo $this->baseUrl();?>/admin/astrology/add"><strong>+ Add</strong></a></li>
		</ol>
	</div>
</div>
    
<div class="contentpanel">
	<form name="filter" id="filter" action="<?php echo $this->baseUrl();?>/admin/astrology/" method="post" role="search">
        <div class="row">
            <div class="col-sm-12" style="background-color:#1d2939; color:#FFF; margin-bottom:15px;"><h5>SEARCH BY:</h5>
        </div>
        <div class="tab-content" style="background-color:#D3D7DB; margin-bottom:0px;">
            <div class="form-group">
                <label class="col-sm-2 control-label">Keyword</label>
                <div class="col-sm-4">
                    <input placeholder="Enter Name Keyword" class="form-control input-sm mb15" name="keyword" id="keyword" value="" type="text">	 
                    <input type="submit" name="search" class="button2" value="Search" />
                    <!--<button class="btn btn-primary btn-block" name="create_lead">Search</button>-->
                </div>
            </div>
        </div>
	</form>
</div>
<div class="info_container">
	<span class="info_text">
		<?php if(!empty($this->messages[0])){ echo $this->messages[0];}?>
	</span>
</div>   
<div class="contentpanel">
	<div class="row">
    	<div class="col-md-12" id="myTable">
        	<table class="table table-striped table-success table-bordered mb30" cellspacing="0" width="100%">
                <thead>
                	<tr>
                        <th width="20">#</th>
                        <th width="20">Date</th>
                        <th width="30">aries</th>
                        <th width="30">taurus</th>
                        <th width="30">gemini</th>
                        <th width="30">cancer</th>
                        <th width="30">leo</th>
                        <th width="30">virgo</th>
                        <th width="30">libra</th>
                        <th width="30">scorpio</th>
                        <th width="30">sagittarius</th>
                        <th width="30">capricorn</th>
                        <th width="30">aquarius</th>
                        <th width="30">pisces</th>
                        <!--<th width="50">Status</th>-->
                        <th width="20">Action</th>
                    </tr>
                </thead>
                <tbody>
                <?php
                $i = 0;
                if($this->data)
				{
					foreach($this->data as $val)
					{
						if($val['isactive'] == 1){
							$stat =	'<i class="fa fa-check-square-o textgreen" title="Active"></i>'; 
							//$stat = "<img src='".$this->baseUrl()."/public/admin/images/green_icon.png' width='12' height='12' alt='Activated' border='0' title='Activated'/>";
						} else {
							$stat =	'<i class="fa fa-square-o textred" title="Inactive"></i>'; 
							//$stat = "<img src='".$this->baseUrl()."/public/admin/images/red_icon.png' width='12' height='12' alt='Inactivated' border='0' title='Inactivated'/>";
						}
                ?>
                        <tr>
                            <td><?php $i++;echo $val['sno'];?>.</td>
                            <td><?php echo ($val['astrodate']);?></td>
                            <td><?php echo substr($val['aries'],0,50);?></td>
                            <td><?php echo substr($val['taurus'],0,50);?></td>
                            <td><?php echo substr($val['gemini'],0,50);?></td>
                            <td><?php echo substr($val['cancer'],0,50);?></td>
                            <td><?php echo substr($val['leo'],0,50);?></td>
                            <td><?php echo substr($val['virgo'],0,50);?></td>
                            <td><?php echo substr($val['libra'],0,50);?></td>
                            <td><?php echo substr($val['scorpio'],0,50);?></td>
                            <td><?php echo substr($val['sagittarius'],0,50);?></td>
                            <td><?php echo substr($val['capricorn'],0,50);?></td>
                            <td><?php echo substr($val['aquarius'],0,50);?></td>
                            <td><?php echo substr($val['pisces'],0,50);?></td>
                            <td align="center">
                            <a href="<?php echo $this->baseUrl();?>/admin/astrology/edit/id/<?php echo $val['idastrology'];?>" title="Edit"><i class="fa fa-edit textblue"></i></a>
                            <?php if($usertype != 2){?>
                                <a href="javascript:void(0)" onclick="deletePost('<?php echo $val['idastrology'];?>')" id="idastrology" title="Delete This?"><i class="fa fa-trash-o textred"></i></a>
                            <?php }?>
                            </td>
                        </tr>
				<?php
					$idastrology = $val['idastrology']; 
					} 
				}?>
                </tbody>
            </table>
            <!-- PAGINATION -->
            <table width="100%" border="0" cellspacing="0" cellpadding="0">
                <tr>
                    <td height="10">
                    <?php 
                    //echo 'I am here ' . count($this->data);
                    //echo $this->pageCount;
                    echo $this->paginationControl($this->data, 'Sliding', 'pagination.phtml');
                    ?>
                    </td>
                </tr>
            </table>
            <!-- / PAGINATION -->
        </div>
  	</div>
</div>

<?php
function getTotalNoView1($post_id){
	$mySQL = "";
	$mySQL = "SELECT COUNT(*) AS totCount FROM astrology WHERE idastrology = '".$isastrology."'";
	$rsTemp = Zend_Registry::get("db")->fetchRow($mySQL);	
	
	if($rsTemp){
		return $rsTemp['totCount'];	
	}
}


?>



        
        
        
        
        
        
        
        
        
        
        
        
        

  

                      