<?php
$_SESSION['timeout'] = 60;
		
include_once('public/fckeditor/fckeditor.php');
//admin session object create
$adminsession=new Zend_Session_Namespace('admin');
$obj = new Default_Model_DbTable_User();
$recods = $obj->getAdminByUser($adminsession->username);
$city = $recods['city'];
$usertype = $recods['user_type'];
?>
	<script type="text/javascript">
    $(document).ready(function() {
            $("#city").change(function() {
            //alert($(this).val());
            url = '<?php echo $this->baseUrl();?>/admin/gallery/ajaxcall?city='+$(this).val();
            //alert(url);
            //$("#block option:selected").remove();
            $.get(url, function(data) {
                $("#location_id").html(data);
            });
            
        });
    
    });
    </script>
	<!-- DATE PICKER -->
    <!--<link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">-->
	<!--<script src="//code.jquery.com/jquery-1.10.2.js"></script>-->
    <script src="<?php echo $this->baseUrl();?>/public/datepicker/jquery-ui.js"></script>
    <script src="<?php echo $this->baseUrl();?>/public/datepicker/jquery.timepicker.js"></script>
    <link href="<?php echo $this->baseUrl();?>/public/datepicker/jquery.timepicker.css" rel="stylesheet" />
    <script>
	$(function() {
    	$( "#scheduleDate" ).datepicker({ 
			minDate: -0, 
			maxDate: "+10D", 
			dateFormat: 'yy-m-d'
         });
  	
		$('#scheduleTime').timepicker();
    });
    </script>
    <!-- / DATE PICKER -->
    
	<!-- / PHOTO PREVIEW -->
    <script type="text/javascript">//<![CDATA[ 
        $(window).load(function () {
            function readPhotoURL(input) {
                //alert(input.files[0].size);
                if (input.files[0].size > 2097152) {
                    alert('Please photo image size maximum 2mb only');
                    $("#image").val('');
					$('#imgPhoto').hide();
                    return (false);
                }
                if (input.files && input.files[0]) {
                    var reader = new FileReader();
                    $('#image').show();
                    reader.onload = function (e) {
						$('#imgPhoto').show();
                        $('#imgPhoto').attr('src', e.target.result);
                    }
                    reader.readAsDataURL(input.files[0]);
                }
            }

            $("#image").change(function () {
                var imgName = $("#image").val();
                var sptImgName;
                var extImageName;
                if ($.browser.mozilla == false) {
                    sptImgName = imgName.split("\\");
                    extImageName = sptImgName[2].split('.');

                } else {
                    sptImgName = imgName;
                    extImageName = sptImgName.split('.');
                }

                var getExt = extImageName[1];
                if (getExt != 'jpg' && getExt != 'jpeg') {
                    alert('Please upload JPG, JPEG file in Photo of the post.');
                    $('#image').val('');
					$('#imgPhoto').hide();
                    return (false);
                } //else { //$('#imgPhoto').show(); }

                if ($.browser.chrome || $.browser.mozilla) {
                    readPhotoURL(this);
                } else if ($.browser.msie) {
                    $('#imgPhoto').show();
                    document.getElementById('imgPhoto').src = $("#txtphoto").val();
                }
            });
        });//]]>  
    </script>
    <!-- / PHOTO PREVIEW -->
    
<?php
$title = '';
if(!empty($_POST['gallerytitle'])) {
	$title = $_POST['gallerytitle'];	
}
$englishurl = '';
if(!empty($_POST['englishurl'])) {
	$englishurl = $_POST['englishurl'];	
}
$metatitle = '';
if(!empty($_POST['metatitle'])) {
	$metatitle = $_POST['metatitle'];	
}
$metakeyword = '';
if(!empty($_POST['metakeyword'])) {
	$metakeyword = $_POST['metakeyword'];	
}
$metadescription = '';
if(!empty($_POST['metadescription'])) {
	$metadescription = $_POST['metadescription'];	
}
?>
    
<div class="pageheader">
      <h2><i class="fa fa-home"></i>Add Gallery</h2>
      <div class="breadcrumb-wrapper">
    
        <ol class="breadcrumb">
         
          <li><a href="<?php echo $this->baseUrl();?>/admin/gallery/"><strong>Back</strong></a></li>
        </ol>
      </div>
    </div>
    
    <div class="contentpanel">
      
      <div class="panel panel-default">
      
        <div class="panel-body panel-body-nopadding">
          
    	<form name="frmpost" id="frmpost" enctype="multipart/form-data" method="post" action="<?php echo $this->baseUrl();?>/admin/gallery/add/">
        <div class="form-group">
        	<div class="col-sm-8">    
                <div class="form-group">
                  <label class="col-sm-4 control-label">Gallery Title</label>
                  <div class="col-sm-8">
                    <input type="text" placeholder="Enter Title" id="gallerytitle" name="gallerytitle" class="form-control" maxlength="100" />
                    <div class="error_container"><span class="error"><?php if(!empty($this->error['title'])){ echo $this->error['title'];}?></span></div>
                  </div>
                </div>
                <div class="form-group">
                  	<label class="col-sm-4 control-label">English URL</label>
                  	<div class="col-sm-8">
                 		<input type="text" placeholder="Enter English URL" id="englishurl" name="englishurl" class="form-control" maxlength="60" />
                 		<div class="error_container"><span class="error"><?php if(!empty($this->error['englishurl'])){ echo $this->error['englishurl'];}?></span></div>
                  	</div>
                </div>
                <div class="form-group">
                <label class="col-sm-4 control-label">Meta Title</label>
                  <div class="col-sm-8">
                    <input type="text" placeholder="Enter Meta title" id="metatitle" name="metatitle" class="form-control" maxlength="60" />
                  </div>
                </div>
                
                <div class="form-group">
                  <label class="col-sm-4 control-label">Meta Keyword</label>
                  <div class="col-sm-8">
                    <textarea class="form-control" id="metakeyword" name="metakeyword" rows="5" ></textarea>
                  </div>
               </div>
                
                <div class="form-group">
                  <label class="col-sm-4 control-label">Meta Description</label>
                  <div class="col-sm-8">
                    <textarea class="form-control" id="metadescription" name="metadescription" rows="5" ></textarea>
                  </div>
                </div>
                <div class="form-group">
                	<label class="col-sm-4 control-label"></label>
                    <div class="col-sm-8">
                    	<button class="btn btn-primary" id="submit" onclick="return validate()">Submit</button>&nbsp;
				 		 <button class="btn btn-default">Cancel</button>
                    </div>
                </div>
                
            </div>
        </div>
        <!-- panel-footer -->
        </form>
      </div><!-- panel -->
      	
