<?php
ob_start();
//if (substr_count($_SERVER['HTTP_ACCEPT_ENCODING'], 'gzip'))
//{
//	header('Content-Encoding: gzip');
//	ob_start('ob_gzhandler');
//} 

$_SESSION['timeout'] = 120;

$adminsession=new Zend_Session_Namespace('admin');
$obj = new Default_Model_DbTable_User();
$recods = $obj->getAdminByUser($adminsession->username);

$adminuserid = '';
$adminusertype = $recods['user_type'];
$adminuserid = $recods['user_id'];
$adminusertype = $recods['user_type'];

$host = $_SERVER['HTTP_HOST'];
//echo $host;
$city = GetBetween("live",".","$host");

//exit;
if ($_SERVER['HTTP_HOST'] == 'localhost') {
	$GLOBALS['city'] = 'gaya';
} else {
	$GLOBALS['city'] = GetBetween("live",".","$host");
}

//echo $GLOBALS['city'] . '<br>';
date_default_timezone_set('Asia/Kolkata');
$toDay = date("D, j M Y G:i:s T");
$currTime = date("h:i:sa");
//echo $toDay . '<br>';
//echo $currTime . '<br>';
//echo date('Y-m-d'); 

$obj = new Default_Model_DbTable_Domain();
$recods = $obj->getDomaincity($GLOBALS['city']);
$domain_hindi = $recods['domain_hindi'];
$domain_english = $recods['domain_english'];
$GLOBALS['state'] = $recods['state'];

$sql = "SELECT facebookURL, twitterURL FROM `domain`";
//echo $sql;
$res = Zend_Registry::get("db")->fetchAll($sql);

if($res){ 
	foreach($res as $val){
		$GLOBALS['facebookURL'] = $val['facebookURL'];
		$GLOBALS['twitterURL'] = $val['twitterURL'];
	}
}
$googleAnalyticTrackingId = '';
$googleSiteVerification = '';
$metaDescription = '';
$metaKeywords = '';
$metaNewsKeywords = '';
$metaAbstract = '';

$GLOBALS['baseUrl'] = $this->baseUrl();

$sql = "SELECT googleAnalyticTrackingId, googleSiteVerification, metaDescription, metaKeywords, metaNewsKeywords, metaAbstract FROM `domain`";
//echo $sql .'<br>';
//exit;
$res = Zend_Registry::get("db")->fetchAll($sql);

if($res){ 
	foreach($res as $val){
		$googleAnalyticTrackingId = $val['googleAnalyticTrackingId'];
		$googleSiteVerification = $val['googleSiteVerification'];
		$metaDescription = $val['metaDescription'];
		$metaKeywords = $val['metaKeywords'];
		$metaNewsKeywords = $val['metaNewsKeywords'];
		$metaAbstract = $val['metaAbstract'];
	}
}
$res = null;

$title = "";
$image = "";	

if ( basename($_SERVER['REQUEST_URI']) != 'search'
	&& strpos(strtolower($_SERVER['REQUEST_URI']), 'strsearch') == ''
	//&& basename($_SERVER['REQUEST_URI']) != 'prakhand'
	&& strpos(strtolower($_SERVER['REQUEST_URI']), 'prakhand') == ''
	&& strpos(strtolower($_SERVER['REQUEST_URI']), 'category') == ''
	&& basename($_SERVER['REQUEST_URI']) != 'category'
	&& basename($_SERVER['REQUEST_URI']) != 'politics'
	&& basename($_SERVER['REQUEST_URI']) != 'crime'
	&& basename($_SERVER['REQUEST_URI']) != 'investigative'
    && basename($_SERVER['REQUEST_URI']) != 'administration'
	&& basename($_SERVER['REQUEST_URI']) != 'education'
	&& basename($_SERVER['REQUEST_URI']) != 'health'
	&& basename($_SERVER['REQUEST_URI']) != 'allcity'
	&& basename($_SERVER['REQUEST_URI']) != 'profile'
	&& basename($_SERVER['REQUEST_URI']) != 'outstanding'
    ){
	if (!empty($this->data['meta_title'])){
		$title = str_replace(',', ' ', $this->data['meta_title']). " " . $domain_english;
	} else {
		$title = substr(str_replace(',', ' ', $this->data['headline']), 0, 175). " " . $domain_english;
	}

	if (!empty($this->data['meta_desc'])){
		$metaDescription = $this->data['meta_desc'];
	}else {
		$metaDescription = substr($this->data['intro'], 0, 175);
	}

	if (!empty($this->data['meta_keyword'])){
		$metaKeywords = $this->data['meta_keyword'];
	}else {
		$metaKeywords = substr($this->data['intro'], 0, 175);
	}

	$image = $this->data['image'];
}

if ($title == ''){
	$title = "Live News India, Hindi Samachar India, Latest World, Politics, Entertainment News";
	$metaDescription = " Live India- Get Live Hindi News from India and around the world, Politics, Entertainment, Crime, Health, Society, Music, Celebs, Women, Fashion and Trending News from India, Read Live India Hindi News and share with Friends";
	$metaKeywords = "Live News India, Hindi Samachar India, World News Live, Politics Hindi News, Entertainment News";
}
//echo '----'. $title;
//exit;

echo chkScheduled();

function chkScheduled(){
	date_default_timezone_set('Asia/Kolkata');
	$date = date('Y-m-d');
	$time = date('H:i:s');
	$created_date = date('Y-m-d h:i:s');

	$mySQL = "";
	$mySQL .= " SELECT post_id, city FROM post WHERE status = '0' AND scheduleDate <> '' AND scheduleTime <> ''";
	$mySQL .= " AND DATE(scheduleDate) <= '".$date."'  AND TIME(scheduleTime) <= '".$time."'";
	$mySQL .= " ORDER BY post_id LIMIT 1";
	//echo 'CHK SHEDULE = ' . $mySQL ."<BR>";
	//exit;
	$rsTemp = Zend_Registry::get("db")->fetchRow($mySQL);
	
	if ($rsTemp){
		$pPostId = '';
		//foreach($rsTemp as $rsVal)
		//{
			$pPostId = $rsTemp['post_id'];
			$pCity = $rsTemp['city'];
			$priority = "";
			$priority = 1;
			//echo '$pPostId = ' . $pPostId . "<hr>";
			if (!empty($pPostId)){
				setAutoPriority1($priority, $pCity);
				$mySQL = "";
				$mySQL .= "UPDATE `post` SET";
				$mySQL .= " scheduleDate = ''";
				$mySQL .= ", scheduleTime = ''";
				$mySQL .= ", priority = '".$priority."'";
				$mySQL .= ", status = '1'";
				$mySQL .= ", created = '".$created_date."'";
				$mySQL .= " WHERE DATE(scheduleDate) <= '".$date."'";	
				$mySQL .= " AND TIME(scheduleTime) <= '".$time."'";	
				$mySQL .= " AND post_id = '".$pPostId."'";	
				//echo $mySQL . '<br>';
				$set = Zend_Registry::get("db")->query($mySQL);
				
			}
		//}
	}
}

function setAutoPriority1($start, $pCity){
	//echo "Start Point = " . $start . "<br>";
	//echo "pCity = " . $pCity . "<br>";
	if($start != ''){ 
		$editedOn = date('Y-m-d h:i:s');
		$i='';
		$pid = "";
		for($i=$start; $i<6; $i++)
		{
			$mySQL = "";
			$mySQL = $mySQL ." SELECT post_id FROM post WHERE city ='".$pCity."' AND `priority` = '".$i."';";
			//echo 'CHK = ' . $mySQL .'<br>';
			$rsTemp1 = Zend_Registry::get("db")->fetchRow($mySQL);
			
            if($rsTemp1){
				//foreach($rsTemp as $upVal){
					$pid = $rsTemp1['post_id'];
					//echo '$pid = ' . $pid .'<BR>';
				//}
				if(!empty($pid)){	
					$j = $i+1;
					$mySQL1 = "";
					$mySQL1 = $mySQL1 ." UPDATE `post` SET";
					if ($i == 5){
						$mySQL1 = $mySQL1 ." `priority` = ''";
					} else {
						$mySQL1 = $mySQL1 ." `priority` = '".$j."'";
					}
					$mySQL1 = $mySQL1 ." , `editedOn` = '".$editedOn."' WHERE city ='".$pCity."'";
					$mySQL1 = $mySQL1 ." AND `post_id` = '".$pid."'";
					$mySQL1 = $mySQL1 ." AND `priority` = '".$i."';";
					//echo '$mySQL1 = ' . $mySQL1 .'<hr>';
					//echo '<hr>';
					$set = Zend_Registry::get("db")->query($mySQL1);
					
				}
			}
			$pid = "";
		}
		//exit;
	}
}
?>
<!DOCTYPE html>
<html lang=en>
<meta charset=utf-8>
<meta content="IE=edge"http-equiv=X-UA-Compatible>
<meta content="width=device-width,initial-scale=1,minimum-scale=1,maximum-scale=1,user-scalable=0"name=viewport>
<meta content=""name=description>
<link href="<?php echo $GLOBALS['baseUrl'];?>/public/images/favicon.ico"rel="shortcut icon"type=image/vnd.microsoft.icon>
<?php
	if ($googleSiteVerification != ''){?>
<meta content="<?php echo $googleSiteVerification;?>"name=google-site-verification>
<?php }?>
<meta content="hi" http-equiv="Content-Language">
<meta content="hindi" name="language">
<meta content="text/html; charset=UTF-8" http-equiv="Content-Type">
<title><?php echo $title;?></title>
<meta content="<?php echo $metaDescription;?>" name="description" itemprop="description">
<meta content="<?php echo $metaKeywords;?>" name=keywords>
<meta content="<?php echo $metaNewsKeywords;?>" name=news_keywords>
<meta content="<?php echo $metaAbstract;?>" name=abstract>
<?php
	/*if (strpos(strtolower($_SERVER['REQUEST_URI']), 'postdetail')) 
	{
	?>
        <!--<meta content="en_US" property="og:locale">
        <meta content="http://<?php echo $_SERVER['HTTP_HOST'] . $this->baseUrl().'/postdetail/index/id/'.$this->data['post_id'].'/'.$GLOBALS['english_url'];?>/" property="og:url">
        <meta content="<?php echo $title;?>" property="og:title">
        <meta content="live<?php echo $city;?>" property="og:site_name">
        <meta content="<?php echo $metaDescription;?>" property="og:description">
        <meta content="article" property="og:type">
        <meta content="http://<?php echo $_SERVER['HTTP_HOST'] . $this->baseUrl();?>/public/products/image/<?php echo $image;?>"property=og:image>-->
	<?php
	}*/
	?>
<meta content="IE=edge" http-equiv="X-UA-Compatible">
<?php if (!empty($image)) {?>
<img alt="<?php echo $title;?>" src="http://<?php echo $_SERVER['HTTP_HOST'] . $this->baseUrl();?>/public/products/image/<?php echo $image;?>" style="display:none" height="1" title="<?php echo $title;?>" width="1">
<link href="http://<?php echo $_SERVER['HTTP_HOST'] . $this->baseUrl();?>/public/products/image/<?php echo $image;?>"rel=image_src>
<?php } else {?>
<img alt="<?php echo $title;?>" src="http://<?php echo $_SERVER['HTTP_HOST'] . $this->baseUrl();?>/public/images/logo_<?php echo $city;?>.png" style="display:none" height="1" title="<?php echo $title;?>" width="1">
<link href="http://<?php echo $_SERVER['HTTP_HOST'] . $this->baseUrl();?>/public/products/image/logo_<?php echo $city;?>.png" rel="image_src">
<?php }?>
<?php
	if($googleAnalyticTrackingId != ''){ 
	?>
<?php
        /*
		<!--<script>
		  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
		  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
		  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
		  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
		  ga('create', '<?php //echo $googleAnalyticTrackingId;?>', 'auto'); ga('send', 'pageview');--> */ ?>
<script>!function(e,i,a,n,t,l,o){e.GoogleAnalyticsObject=t,e[t]=e[t]||function(){(e[t].q=e[t].q||[]).push(arguments)},e[t].l=1*new Date,l=i.createElement(a),o=i.getElementsByTagName(a)[0],l.async=1,l.src=n,o.parentNode.insertBefore(l,o)}(window,document,"script","//www.google-analytics.com/analytics.js","ga"),ga("create","<?php echo $googleAnalyticTrackingId;?>","auto",{allowLinker:!0}),ga("require","displayfeatures"),ga("require","linker"),ga("linker:autoLink",["liveindia.live","livecities.in","liveindiahindi.com"]),ga("send","pageview")</script>
<?php 
	}
	?>
<link href="<?php echo $GLOBALS['baseUrl']?>/public/css/custom.css"rel=stylesheet>
<link href="<?php echo $GLOBALS['baseUrl']?>/public/css/color.css"rel=stylesheet>
<link href="<?php echo $GLOBALS['baseUrl']?>/public/css/mega-menu.css"rel=stylesheet>
<link href="<?php echo $GLOBALS['baseUrl']?>/public/css/bootstrap.css"rel=stylesheet>
<link href="<?php echo $GLOBALS['baseUrl']?>/public/css/bootstrap-theme.min.css"rel=stylesheet>
<link href="<?php echo $GLOBALS['baseUrl']?>/public/css/materialize.css"rel=stylesheet>
<link href="<?php echo $GLOBALS['baseUrl']?>/public/css/font-awesome.min.css"rel=stylesheet>
<link href="<?php echo $GLOBALS['baseUrl']?>/public/css/owl.slider.css"rel=stylesheet>
<link href="<?php echo $GLOBALS['baseUrl']?>/public/css/style.css"rel=stylesheet>
<!--[if lt IE 9]><script src=https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js></script><script src=https://oss.maxcdn.com/respond/1.4.2/respond.min.js></script><![endif]-->
<?php
	/*
    <!--<link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">
    <script src="//code.jquery.com/jquery-1.10.2.js"></script>
    <script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
    <script>
      $(function() {
        var icons = {
          header: "ui-icon-circle-arrow-e",
          activeHeader: "ui-icon-circle-arrow-s"
        };
        $( "#rashiphal" ).accordion({
            heightStyle: "content",
            collapsible: true,
            icons: icons
        });
        $( "#toggle" ).button().click(function() {
          if ( $( "#rashiphal" ).accordion( "option", "icons" ) ) {
            $( "#rashiphal" ).accordion( "option", "icons", null );
          } else {
            $( "#rashiphal" ).accordion( "option", "icons", icons );
          }
        });
      });
      </script>-->
	  */
	  ?>
<script>var _rys=jQuery.noConflict();_rys("document").ready(function(){_rys(window).scroll(function(){_rys(this).scrollTop()>1?_rys(".cp-megamenu").addClass("f-nav"):(_rys(".cp-megamenu").removeClass("f-nav"),$("#navDiv").css("margin-right","0"))})})</script>
<div style="text-align:center;margin:5px 0">
  <?php //echo getAds(1, 1)?>
  <style type="text/css">
.CM_LI_HP_TOP { width: 320px; height: 50px; }
@media (min-width:300px) { .CM_LI_HP_TOP { width: 320px; height: 100px; } }
@media (min-width:480px) { .CM_LI_HP_TOP { width: 468px; height: 60px; } }
@media (min-width:730px) { .CM_LI_HP_TOP { width: 728px; height: 90px; } }
</style>
  <ins class="adsbygoogle CM_LI_HP_TOP "
style="display:inline-block;"
data-ad-client="ca-pub-7910693805653243"
data-ad-slot="8449625813"></ins> 
  <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script> 
  <script>(adsbygoogle = window.adsbygoogle || []).push({});</script></div>
<div class="wrapper" id="wrapper">
<div class="cp-header" id="cp-header">
  <div class="cp-mega-menu-full-bg cp-megamenu">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <div class="cp-mega-menu"><span class="cp-md-2" id="mobilelogo"><a href="<?php echo $GLOBALS['baseUrl']?>/" class="mobilelogo"><img alt="" src="<?php echo $GLOBALS['baseUrl']?>/public/images/footer-logo.png"style="margin:17px 5px;width:100px"></a></span>
            <label class=text17 for=mobile-button style=padding-right:5px><i class="text17 fa fa-bars"></i> <span class=text17>Menu</span></label>
            <input id=mobile-button type=checkbox>
            <ul class="collapse main-menu">
              <li id="micrologo" class="icon-bar slogo1"style=background-color:#FF1489><a href="<?php echo $GLOBALS['baseUrl']?>/"><img alt=""src="<?php echo $GLOBALS['baseUrl']?>/public/images/logo-micon.png"></a></li>
              <?php echo getTopMenuCategoryWisePost('Top Menu')?>
              <li id="micrologo" class="icon-bar logo-bar"style="padding:15px 0 0 0;float:right"><a href="<?php echo $GLOBALS['baseUrl']?>/"><img alt=""src="<?php echo $GLOBALS['baseUrl']?>/public/images/logo-bar.png"></a>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
