<script type="text/javascript">
	function deleteRec(id){
		var iAgree = confirm("You are sure want to delete?.")
		if (iAgree == true){
			document.location.href="<?php echo $this->baseUrl();?>/admin/category/delete/id/" + id;
			return(true);
		} else {
			return (false);
		}
	}
</script>
<div class="pageheader">
      <h2><i class="fa fa-home"></i>Manage Category</h2>
      <div class="breadcrumb-wrapper">
    
        <ol class="breadcrumb">
         
          <li><a href="<?php echo $this->baseUrl();?>/admin/category/add"><strong>+ Add</strong></a></li>
        </ol>
      </div>
    </div>
   
    
<div class="info_container"><span class="info_text">
<?php if(!empty($this->messages[0])){ echo $this->messages[0];}?>
</span></div>

    <div class="contentpanel">
    
     
      <div class="row">
     <div class="col-md-12">
     <form name="frmcategory" id="frmcategory" method="post" action="<?php echo $this->baseUrl();?>/admin/category/add">
           <table class="table table-success mb30">
                    <thead>
                      <tr>
                        <th width="10">#</th>
						<th width="300">Category</th>
						<th width="80">Position</th>
						<th width="80">Date</th>
						<th width="20">Status</th>
						<th width="30">Action</th>
                      </tr>
                    </thead>
                    <?php
				  $i = 0;
				  if($this->data){
				  foreach($this->data as $val){
					  
					  if($val['status'] == 1){
							$stat =	'<i class="fa fa-check-square-o textgreen" title="Active"></i>'; 
							//$stat = "<img src='".$this->baseUrl()."/public/admin/images/green_icon.png' width='12' height='12' alt='Activated' border='0' title='Activated'/>";
						}else{
							$stat =	'<i class="fa fa-square-o textred" title="Inactive"></i>'; 
							//$stat = "<img src='".$this->baseUrl()."/public/admin/images/red_icon.png' width='12' height='12' alt='Inactivated' border='0' title='Inactivated'/>";
						}
				   ?>
                    <tbody>
                      <tr>
                       <td><?php $i++;echo $i;?>.</td>
                       <td><?php echo $val['category'];?></td>
                       <td><?php echo $val['position'];?></td>
                       <td><?php echo $val['created'];?></td>
                       <td><a href="<?php echo $this->baseUrl();?>/admin/category/active/id/<?php echo $val['category_id'];?>" title="status"><?php echo $stat;?></a></td>
                       <td><!--<a href="#" title="view"><i class="fa fa-search"></i></a>&nbsp;&nbsp;-->
                       <a href="<?php echo $this->baseUrl();?>/admin/category/edit/id/<?php echo $val['category_id'];?>" title="Edit"><i class="fa fa-edit textblue"></i></a>
                                <a href="javascript:void(0)" onclick="deleteRec('<?php echo $val['category_id'];?>')" id="delPost" title="Delete This?"><i class="fa fa-trash-o textred"></i></a>
                       </td>      
						 </tr>
					<?php } }?>
                 </tbody>
                </table>
                </form>
        
        
        
        
        
        
        
        
        
        
        
        
        
        

  

                      