 <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Admin Template - Login</title>
<link href="<?php echo $this->baseUrl();?>/public/admin/styles/layout.css" rel="stylesheet" type="text/css" />
<link href="<?php echo $this->baseUrl();?>/public/admin/styles/login.css" rel="stylesheet" type="text/css" />
<!-- Theme Start -->
<link href="<?php echo $this->baseUrl();?>/public/admin/themes/blue/styles.css" rel="stylesheet" type="text/css" />
<!-- Theme End -->

</head>
<body>
	<div id="logincontainer">
    	<div id="loginbox">
        	<div id="loginheader">
            	<img src="<?php echo $this->baseUrl();?>/public/admin/themes/blue/img/cp_logo_login.png" alt="Control Panel Login" />
            </div>
            <div id="innerlogin">


<div align="center"><div align="center" class="divlogin" >
<form id="form1" name="form1" method="post" action="">

<table width="90%" cellspacing="1" cellpadding="3" border="0" align="center" class="tableset">
                                    <tbody><tr>
                                        <td align="left"><div style="float:left"><span ><h1> <img src="<?php echo $this->baseUrl();?>/public/img/forgot1.png" align="absmiddle">&nbsp;&nbsp;Forgot Password</h1>Please use this wizard to help you recover your password.<span ></div><div style="float:right"><span><a href="<?php echo $this->baseUrl();?>/admin/" style="text-decoration:none; color:#666666;" ><img src="<?php echo $this->baseUrl();?>/public/img/back.png" alt="Inactive" border="0" align="absmiddle"/>&nbsp;<strong>Back</strong></a></span></div>
		
		
 <br><br><br><br>
<table width="100%"  cellspacing="5" cellpadding="2" border="0"  align="center"  class="tableset">
			<tbody>
		 <tr >
				<td align="center" colspan="2" class="errormsg"><?php if (count($this->messages)) : ?>
<div id="messages">
<?php foreach ($this->messages as $message) : ?>
    <li><?php echo $this->escape($message); ?></li>
<?php endforeach; ?>
</div>
<?php endif; ?>
</td>
			</tr>
			<tr>
				<td align="Left" width="25%" ><span><strong>E-mail Address</strong></span></td>
				<td align="Left" width="75%"><input type="email" id="cemail" name="email" class="text_field" required /></td>
			</tr>
			
			<tr >
				<td align="center" colspan="2"><span>&nbsp;</span></td>
			</tr>
			<tr >
				<td align="center" colspan="2" class="buttons" ><table width="100%" border="0" cellspacing="2" cellpadding="2">
                  <tr>
                    <td width="30%" align="right"  style="padding-left:150px;"><input name="cancel" type="reset" value="Cancel" class="read_more" style="border:none;"/></td>
                    <td width="70%"><input name="submit" type="submit" value="Submit" class="read_more" style="border:none;"/></td>
                  </tr>
                </table>				  </td>
			</tr>
			<tr >
				<td align="Left" colspan="2" >&nbsp;
</td>
			</tr>
			
		</tbody></table>

		<div>

			
		</div>
		
                                        </td>
                                    </tr>
                                </tbody></table>

</form>

</div></div>


</body>
</html>
