<?php
include_once('public/fckeditor/fckeditor.php');
$idContent = $this->data['idContent'];

$sql = "SELECT * FROM `content` WHERE `idContent` = '$idContent'";
//echo $sql;die(); 
$res = Zend_Registry::get("db")->fetchAll($sql);

//$objMeta = new Default_Model_DbTable_Category();
//$adminMetaVals = $objMeta->getMetaKeyVal($pid);
//$category = $objMeta->getMetaKeyVal($postid);
//$special = explode(',',$category);
//print_r($special);die();

$adminsession=new Zend_Session_Namespace('admin');
$obj = new Default_Model_DbTable_User();

$recods = $obj->getAdminByUser($adminsession->username);
$city = $recods['city'];
$usertype = $recods['user_type'];

function selectedCatgories($post_id, $category_id){
	if ($post_id != ''){
		$category_name = '';
		$sql = "";
		$sql = "SELECT category_name FROM `post_category` WHERE `post_id` = '".$post_id."' AND category_id = '".$category_id."'";
		//echo $sql; 
		$rsCat = Zend_Registry::get("db")->fetchAll($sql);	
		if($rsCat){ foreach($rsCat as $resCat){
			$category_name = $resCat['category_name'];
		}}
		return $category_name;
	}
}
?>
<div class="pageheader">
    <h2><i class="fa fa-home"></i>Edit Content</h2>
    <div class="breadcrumb-wrapper">
    	<ol class="breadcrumb">
    		<li><a href="<?php echo $this->baseUrl();?>/admin/content/"><strong>Back</strong></a></li>
    	</ol>
    </div>
</div>
<form name="frmpost" id="frmpost" method="post" action="<?php echo $this->baseUrl();?>/admin/content/edit/id/<?php echo $this->data['idContent'];?>">
<div class="contentpanel">
	<div class="panel panel-default">
		<div class="panel-body panel-body-nopadding">
            <div class="form-group">
                <label class="col-sm-2 control-label">Heading</label>
                <div class="col-sm-10">
                    <select class="select2" name="contentHeading" id="contentHeading" placeholder="Select">
              		<option value=""></option>
                    <option value="About Us" <?php if ($this->data['contentHeading'] == 'About Us') { echo 'Selected'; }?>>About Us</option>
                    <option value="Privacy" <?php if ($this->data['contentHeading'] == 'Privacy') { echo 'Selected'; }?>>Privacy</option>
                    <option value="Contact Us" <?php if ($this->data['contentHeading'] == 'Contact Us') { echo 'Selected'; }?>>Contact Us</option>
       		  	</select>
                </div>
            </div>
			<div class="form-group">
                <label class="col-sm-2 control-label">Content</label>
                <div class="col-sm-10">
                    <?php
                    $oFCKeditor = new FCKeditor('contentDetail');
                    $oFCKeditor->BasePath = $this->baseUrl()."/public/fckeditor/";
                    $oFCKeditor->ToolbarSet = 'MyToolbar';
                	$oFCKeditor->Value = $this->data['contentDetail'];
                    $oFCKeditor->Create();
                    $oFCKeditor->Height = 900;
                    $oFCKeditor->Width = 700;
                    ?>
                </div>
            </div>
            <div class="form-group">
                <div class="col-sm-12" align="center">
                    <input type="hidden" name="idContent" id="idContent" value="<?php echo $this->data['idContent'];?>" />
                    <button class="btn btn-primary" id="submit" onclick="return validate()">Update</button>
                    <button class="btn btn-default">Cancel</button>
                </div>
            </div>
		</div>
	</div>
</div>
</form>	
</div><!-- panel -->
		<script>
	  	function validate() {
			var contentHeading = $('#contentHeading').val();
			var content = $('#content').val();
			//alert('content = '+ content);
			
			if($.trim(contentHeading) == '' || contentHeading == null){
				alert('Please select Heading');
				$('#contentHeading').focus();
				return (false);
			}
			if($.trim(contenDetail) == '' || contenDetail == null){
				alert('Please fill content');
				$('#contenDetail').focus();
				return (false);
			}
		};
	  	</script>
