<?php
$adminsession = new Zend_Session_Namespace('admin');
$obj = new Default_Model_DbTable_User();
$recods = $obj->getAdminByUser($adminsession->username);
$usertype = $recods['user_type'];
?>
<script type="text/javascript">
	function deleteRec(id){
		var iAgree = confirm("You are sure want to delete?.")
		if (iAgree == true){
			document.location.href="<?php echo $this->baseUrl();?>/admin/content/delete/id/" + id;
			return(true);
		} else {
			return (false);
		}
	}
</script>
<div class="pageheader">
	<h2><i class="fa fa-home"></i>Manage Site Content</h2>
	<div class="breadcrumb-wrapper">
		<ol class="breadcrumb">
			<li><a href="<?php echo $this->baseUrl();?>/admin/content/add"><strong>+ Add</strong></a></li>
		</ol>
	</div>
</div>
<div class="info_container">
	<span class="info_text">
		<?php if(!empty($this->messages[0])){ echo $this->messages[0];}?>
	</span>
</div>   
<div class="contentpanel">
	<div class="row">
    	<div class="col-md-12">
           	<table class="table table-success mb30">
                <thead>
                	<tr>
                        <th width="10">#</th>
                        <th width="80">Heading</th>
                        <th width="300">Detail</th>
                        <th width="43">Action</th>
                    </tr>
                </thead>
                <tbody>
                <?php
                $i = 0;
                if($this->data)
				{
					foreach($this->data as $val)
					{
				?>
                        <tr>
                            <td><?php $i++;echo $i;?>.</td>
                            <td><b><?php echo $val['contentHeading'];?></b></td>
                            <td align="justify"><?php echo $val['contentDetail'];?></td>
                            <td align="center"><!--<a href="#" title="view"><i class="fa fa-search"></i></a>&nbsp;&nbsp;-->
                                <a href="<?php echo $this->baseUrl();?>/admin/content/edit/id/<?php echo $val['idContent'];?>" title="Edit"><i class="fa fa-edit textblue"></i></a>
                                <a href="javascript:void(0)" onclick="deleteRec('<?php echo $val['idContent'];?>')" id="delPost" title="Delete This?"><i class="fa fa-trash-o textred"></i></a>
                            </td>
                            <?php //}?>
                        </tr>
				<?php
					$idContent = $val['idContent']; 
					} 
				}?>
                </tbody>
            </table>
    	</div>
  	</div>
    <!-- PAGINATION -->
    <div class="row">
    	<div class="col-md-12">
        <?php //include_once('pagination.php');?>
        <?php //include_once('/admin/views/script/pagination.phtml');?>
        </div>
   	</div>
     <!-- / PAGINATION -->
</div>
