<?php
ini_set('memory_limit', '256M');

$adminsession = new Zend_Session_Namespace('admin');
$obj = new Default_Model_DbTable_User();
$recods = $obj->getAdminByUser($adminsession->username);
$usertype = $recods['user_type'];
?>
<script type="text/javascript">
	function deletePost(post_id){
		var iAgree = confirm("You are sure want to delete?.")
		if (iAgree == true){
			document.location.href="<?php echo $this->baseUrl();?>/admin/post/delete/id/" + post_id;
			return(true);
		} else {
			return (false);
		}
	}
</script>
<!-- SHARE THIS -->
<!--<script type="text/javascript">var switchTo5x=true;</script>-->
<script type="text/javascript" src="http://w.sharethis.com/button/buttons.js"></script>
<script type="text/javascript">stLight.options({publisher: "9ee8c443-57cf-44ea-8e67-11693a461baf", doNotHash: false, doNotCopy: false, hashAddressBar: false});
</script>
<!-- / SHARE THIS -->

<!-- DATE PICKER -->
<!--<link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">-->
<!--<script src="//code.jquery.com/jquery-1.10.2.js"></script>-->
<script src="/liveindia.live/public/datepicker/jquery-ui.js"></script>
<script src="/liveindia.live/public/datepicker/jquery.timepicker.js"></script>
<link href="/liveindia.live/public/datepicker/jquery.timepicker.css" rel="stylesheet" />
<script>
$(function() {
    //var year = d.getFullYear();
    //d.setFullYear(year);
    $("#createdfrom").datepicker({
        //minDate: -0
        defaultDate: "+1w"
        //, changeMonth: true
        //, changeYear: true
        , dateFormat: 'yy-m-d'
        //, yearRange: '1954:' + year + ''
        //, defaultDate: d
        //, numberOfMonths: 2
        , onClose: function (selectedDate) {
            $("#createdto").datepicker("option", "minDate", selectedDate);
        }
    });

    // Employee Join To Date on Registration.aspx //
    $("#createdto").datepicker({
        minDate: -0
        , defaultDate: "+1w"
        //, changeMonth: true
        //, changeYear: true
        , dateFormat: 'yy-m-d'
        //, yearRange: '1954:' + year + ''
        //, defaultDate: d
        //, numberOfMonths: 2
        , onClose: function (selectedDate) {
            $("#createdfrom").datepicker("option", "maxDate", selectedDate);
        }
    });
});
</script>
<!-- / DATE PICKER -->

<div class="pageheader">
	<h2><i class="fa fa-home"></i>Manage Posts</h2>
	<div class="breadcrumb-wrapper">
		<ol class="breadcrumb">
			<li><a href="<?php echo $this->baseUrl();?>/admin/post/add"><strong>+ Add</strong></a></li>
		</ol>
	</div>
</div>
    
<div class="contentpanel">
	<form name="filter" id="filter" action="<?php echo $this->baseUrl();?>/admin/post/" method="post" role="search">
        <div class="row">
            <div class="col-sm-12" style="background-color:#1d2939; color:#FFF; margin-bottom:15px;"><h5>SEARCH BY:</h5>
        </div>
        <div class="tab-content" style="background-color:#D3D7DB; margin-bottom:0px;">
            <div class="form-group">
                <label class="col-sm-1 control-label">Keyword</label>
                <div class="col-sm-3">
                    <input placeholder="Enter Name Keyword" class="form-control input-sm mb15" name="keyword" id="keyword" value="" type="text">	 
                </div>
                <label class="col-sm-1 control-label" style="text-align:center;">Date</label>
                <div class="col-md-1">
                	<input placeholder="From Date"class="form-control" id="createdfrom" name="createdfrom" type="text" value="<?php //echo $created; ?>" maxlength="10" style="width:90px;" autocomplete="off" />
                </div>
				<div class="col-md-1">
                	<input placeholder="To Date" class="form-control" id="createdto" name="createdto" type="text" value="<?php //echo $created; ?>" maxlength="10" style="width:90px;" autocomplete="off" />
                </div>
				<label class="col-sm-1 control-label" style="text-align:center;">Order By</label>
                <div class="col-md-2">
                	<select name="orderby" class="select2">
						<option value="created ASC">Created On ASC</option>
						<option value="created DESC">Created ON DESC</option>
					</select>
                </div>
                <div class="col-sm-2">
                    <input type="submit" name="search" class="button2" value="Search" />
                    <!--<button class="btn btn-primary btn-block" name="create_lead">Search</button>-->
                </div>  
            </div>
        </div>
	</form>
</div>
<div class="info_container">
	<span class="info_text">
		<?php if(!empty($this->messages[0])){ echo $this->messages[0];}?>
	</span>
</div>   
<div class="contentpanel">
	<div class="row">
    	<div class="col-md-12" id="myTable">
        	<table class="table table-striped table-success table-bordered mb30" cellspacing="0" width="100%">
                <thead>
                	<tr>
                        <th width="20">#</th>
                        <th width="300">Headline</th>
                        <!--<th width="10">View</th>-->
                        <?php if($usertype != 2){?>
                        	<th width="50">Share</th>
                       	<?php }?>
                        <th width="81">City</th>
                        <th width="96">Posted By</th>
                        <th width="97">Edited By</th>
                        <th width="81">Date</th>
                        <th width="78">Status</th>
                        <th width="100">Action</th>
                    </tr>
                </thead>
                <tbody>
                <?php
                $i = 0;
                if($this->data)
				{
					foreach($this->data as $val)
					{
						if($val['status'] == 1){
							$stat =	'<i class="fa fa-check-square-o textgreen" title="Active"></i>'; 
							//$stat = "<img src='".$this->baseUrl()."/public/admin/images/green_icon.png' width='12' height='12' alt='Activated' border='0' title='Activated'/>";
						} else {
							$stat =	'<i class="fa fa-square-o textred" title="Inactive"></i>'; 
							//$stat = "<img src='".$this->baseUrl()."/public/admin/images/red_icon.png' width='12' height='12' alt='Inactivated' border='0' title='Inactivated'/>";
						}
                ?>
                        <tr>
                            <td><?php $i++;echo $val['sno'];?>.</td>
                            <td><?php echo substr($val['headline'],0,200);?></td>
                            <!--<td><?php //echo getTotalNoView($val['post_id']);?></td>-->
                           	<?php if($usertype != 2){?>
                                <td nowrap="nowrap">
                                    <span class='st_facebook' st_url="http://<?php echo 'www.live'.strtolower($val['city']).'.com/postdetail/index/id/'.$val['post_id'].'/'.$val['english_url'];?>" st_title="<?php echo $val['headline'];?>"></span>
                                    <span class='st_twitter' st_url="http://<?php echo 'www.live'.strtolower($val['city']).'.com/postdetail/index/id/'.$val['post_id'].'/'.$val['english_url'];?>" st_title="<?php echo $val['headline'];?>"></span>
                                    <span class='st_googleplus' st_url="http://<?php echo 'www.live'.strtolower($val['city']).'.com/postdetail/index/id/'.$val['post_id'].'/'.$val['english_url'];?>" st_title="<?php echo $val['headline'];?>"></span>
                                    <span class='st_whatsapp' st_url="http://<?php echo 'www.live'.strtolower($val['city']).'.com/postdetail/index/id/'.$val['post_id'].'/'.$val['english_url'];?>" st_title="<?php echo $val['headline'];?>"></span>
                                </td>
                           	<?php }?>
                            <td><?php echo $val['city'];?></td>
                            <td><?php echo $val['user_name'];?></td>
                            <td><?php echo $val['edited_by'];?></td>
                            <td nowrap="nowrap"><?php echo $val['createdOn'];?></td>
                            <?php if($usertype == 2){?>
                                <td align="center"><a href=""><?php echo $stat;?></a></td>
                            <?php } else {?>
                                <td align="center"><a href="<?php echo $this->baseUrl();?>/admin/post/active/id/<?php echo $val['post_id'];?>"><?php echo $stat;?></a></td>
                            <?php }?>
                            <td align="center"><!--<a href="#" title="view"><i class="fa fa-search"></i></a>&nbsp;&nbsp;-->
                            <a href="<?php echo $this->baseUrl();?>/postdetail/index/id/<?php echo $val['post_id'];?>/<?php echo $val['english_url'];?>/" title="View" target="_blank"><i class="fa fa-eye textgreen"></i></a>
                            <a href="<?php echo $this->baseUrl();?>/admin/post/edit/id/<?php echo $val['post_id'];?>" title="Edit"><i class="fa fa-edit textblue"></i></a>
                            <?php if($usertype != 2){?>
                                <!--<a href="<?php //echo $this->baseUrl();?>/admin/post/copy/id/<?php echo $val['post_id'];?>" title="Copy"><i class="fa fa-files-o textgreen"></i></a>-->
                                <a href="javascript:void(0)" onclick="deletePost('<?php echo $val['post_id'];?>')" id="delPost" title="Delete This?"><i class="fa fa-trash-o textred"></i></a>
                            <?php }?>
                            </td>
                        </tr>
				<?php
					$post_id = $val['post_id']; 
					} 
				}?>
                </tbody>
            </table>
            <!-- PAGINATION -->
            <table width="100%" border="0" cellspacing="0" cellpadding="0">
                <tr>
                    <td height="10">
                    <?php 
                    //echo 'I am here ' . count($this->data);
                    //echo $this->pageCount;
                    echo $this->paginationControl($this->data, 'Sliding', 'pagination.phtml');
                    ?>
                    </td>
                </tr>
            </table>
            <!-- / PAGINATION -->
        </div>
  	</div>
    	
    
     
</div>

<?php
function getTotalNoView1($post_id){
	$mySQL = "";
	$mySQL = "SELECT COUNT(*) AS totCount FROM postview WHERE post_id = '".$post_id."'";
	$rsTemp = Zend_Registry::get("db")->fetchRow($mySQL);	
	
	if($rsTemp){
		return $rsTemp['totCount'];	
	}
}
?>



        
        
        
        
        
        
        
        
        
        
        
        
        

  

                      