<form name="frm" action="" method="post">

<table width="461" border="0" cellspacing="0" cellpadding="0">
 <tr>
    <td colspan="3"><h1 align="center">Change Password</h1></td>
    
  </tr>
 <tr>
    <td colspan="3">
    <?php if(isset($this->error)): ?>
    <p class="error"><?php echo $this->error;?></p>
    <?php endif;?>
    </td>
    
  </tr>
  <tr>
    <td width="234">Old Password</td>
    <td width="8">*</td>
    <td width="219"><input type="password" name="oldPass"></td>
  </tr>
  <tr>
    <td>New Password</td>
    <td>*</td>
    <td><input type="password" name="newPassword"></td>
  </tr>
  <tr>
    <td>Confirm Password</td>
    <td>*</td>
    <td><input type="password" name="cnewPassword"></td>
  </tr>
  <tr>
    <td colspan="3">&nbsp;</td>
    
  </tr>
  <tr>
    <td colspan="3" align="center"><input type="submit" name="submit" value="Change Password" class="btn"></td>
    
  </tr>
</table>
</form>
