<?php
include_once('public/fckeditor/fckeditor.php');
//admin session object create
$adminsession=new Zend_Session_Namespace('admin');
$obj = new Default_Model_DbTable_User();
$recods = $obj->getAdminByUser($adminsession->username);
$city = $recods['city'];
$usertype = $recods['user_type'];
?>
<div class="pageheader">
      <h2><i class="fa fa-home"></i>Add Content</h2>
      <div class="breadcrumb-wrapper">
    
        <ol class="breadcrumb">
         
          <li><a href="<?php echo $this->baseUrl();?>/admin/content/"><strong>Back</strong></a></li>
        </ol>
      </div>
    </div>
    
    <div class="contentpanel">
      
      <div class="panel panel-default">
      
        <div class="panel-body panel-body-nopadding">
          
    <form name="frmpost" id="frmpost" method="post" action="<?php echo $this->baseUrl();?>/admin/content/add">
            
            <div class="form-group">
              	<label class="col-sm-2 control-label">Heading</label>
              	<div class="col-sm-10">
                <select class="select2" name="contentHeading" id="contentHeading" placeholder="Select">
              		<option value=""></option>
                    <option value="About Us">About Us</option>
                    <option value="Privacy">Privacy</option>
                    <option value="Contact Us">Contact Us</option>
       		  	</select>
              </div>
            </div>
            
            <div class="form-group">
              <label class="col-sm-2 control-label">Content</label>
              <div class="col-sm-10">
              	<?php
                $oFCKeditor = new FCKeditor('contentDetail');
                $oFCKeditor->BasePath = $this->baseUrl()."/public/fckeditor/";
				$oFCKeditor->ToolbarSet = 'MyToolbar';
				$oFCKeditor->Value = '';
                $oFCKeditor->Create();
                $oFCKeditor->Height = 900;
                $oFCKeditor->Width = 700;
                ?>
              </div>
            </div>
        
        <div class="panel-footer">
			 <div class="row">
				<div class="col-sm-7 col-sm-offset-3">
				  <button class="btn btn-primary" id="submit" onclick="return validate()">Submit</button>
				  <button class="btn btn-default">Cancel</button>
				</div>
			 </div>
		  </div><!-- panel-footer -->
        </form>
      </div><!-- panel -->
      	<script>
	  	function validate() {
			var contentHeading = $('#contentHeading').val();
			var content = $('#content').val();
			//alert('content = '+ content);
			
			if($.trim(contentHeading) == '' || contentHeading == null){
				alert('Please select Heading');
				$('#contentHeading').focus();
				return (false);
			}
			if($.trim(contenDetail) == '' || contenDetail == null){
				alert('Please fill content');
				$('#contenDetail').focus();
				return (false);
			}
		};
	  	</script>
