<div class="pageheader">
      <h2><i class="fa fa-home"></i>Add Category</h2>
      <div class="breadcrumb-wrapper">
    
        <ol class="breadcrumb">
         
          <li><a href="<?php echo $this->baseUrl();?>/admin/category/"><strong>Back</strong></a></li>
        </ol>
      </div>
    </div>
    
    <div class="contentpanel">
      
      <div class="panel panel-default">
      
        <div class="panel-body panel-body-nopadding">
          
     <form class="form-horizontal form-bordered" name="form1" id="form1" action="<?php echo $this->baseUrl();?>/admin/category/add" method="post">
            
            <div class="form-group">
              <label class="col-sm-3 control-label">Category</label>
              <div class="col-sm-6">
                <input type="text" id="category" name="category" placeholder="Enter Category" class="form-control" maxlength="100" required />
              </div>
            </div>
            <div class="form-group">
                <label class="col-sm-3 control-label">Position</label>
                <div class="col-sm-3">
                    <select name="position" id="position" class="select2">
                        <option value="">Select</option>
                        <option value="Top Menu">Top Menu</option>
                        <option value="Right Column">Right Column</option>
                        <option value="Main Body On Page">Main Body On Page</option>
                    </select>
                </div>
            </div>
            <label class="col-sm-3 control-label">Sort order</label>
                <div class="col-sm-3">
                    <input type="text" id="sort" name="sort" placeholder="Enter Sort order" class="form-control" maxlength="2" required />
                </div>
            </div>
            
            
        <div class="panel-footer">
			 <div class="row">
				<div class="col-sm-6 col-sm-offset-3">
				  <button class="btn btn-primary">Submit</button>&nbsp;
				  <button class="btn btn-default">Cancel</button>
				</div>
                </form>
			 </div>
		  </div><!-- panel-footer -->
        
      </div><!-- panel -->
