<?php
$host = $_SERVER['HTTP_HOST'];
function GetBetween1($var1="",$var2="",$pool){
	$temp1 = strpos($pool,$var1)+strlen($var1);
	$result = substr($pool,$temp1,strlen($pool));
	$dd=strpos($result,$var2);
	if($dd == 0){
		$dd = strlen($result);
	}
	return substr($result,0,$dd);
}
if ($_SERVER['HTTP_HOST'] == 'localhost') {
	$GLOBALS['city'] = 'gaya';
} else {
	$GLOBALS['city'] = GetBetween("live",".","$host");
}

$GLOBALS['baseUrl'] = $this->baseUrl();
?>
	<!-- CATEGORY WISE NEWS -->
  <?php echo getMainBodyCategoryWisePost('Top News')?>
  <?php echo getMainBodyCategoryWisePost("Don't Miss")?>
  <?php echo getMainBodyCategoryWisePost('Nation')?>
  <?php echo getMainBodyCategoryWisePost('World')?>
  <?php echo getMainBodyCategoryWisePost('Most Popular')?>
  <?php echo getMainBodyCategoryWisePost('Sports')?>
  <?php echo getMainBodyCategoryWisePost('Bollywood')?>
  <?php echo getMainBodyCategoryWisePost('Business')?>
  <?php echo getMainBodyCategoryWisePost('Lifestyle')?>
  <?php echo getMainBodyCategoryWisePost('Tech')?>
  <?php echo getMainBodyCategoryWisePost('Auto')?>
  
  <!-- / CATEGORY WISE NEWS -->
  