<div class="pageheader">
      <h2><i class="fa fa-home"></i>Add State,City & Block</h2>
      <div class="breadcrumb-wrapper">
    
        <ol class="breadcrumb">
         
          <li><a href="<?php echo $this->baseUrl();?>/admin/statecity/"><strong>Back</strong></a></li>
        </ol>
      </div>
    </div>
    
    <div class="contentpanel">
      
      <div class="panel panel-default">
      
        <div class="panel-body panel-body-nopadding">
          
     <form class="form-horizontal form-bordered" name="form1" id="form1" action="<?php echo $this->baseUrl();?>/admin/statecity/add" method="post">
            
             <div class="form-group">
              <label class="col-sm-3 control-label">Select State</label>
              <div class="col-sm-5">
                <select class="select2" id="state" name="state" data-placeholder="Choose a State..." required>
                  <option value=""></option>
                  <option value="bihar">Bihar</option>
                  <option value="jharkhand">Jharkhand</option>
                  <option value="uttar Pradesh">Uttar Pradesh</option>
                  <option value="uttarakhand">Uttarakhand</option>
                  <option value="rajasthan">Rajasthan</option>
                  </select>
              </div>
            </div>   
            
            <div class="form-group">
              <label class="col-sm-3 control-label">Select City</label>
              <div class="col-sm-5">
                <select class="select2" id="city" name="city" data-placeholder="Choose a City..." required>
                  <option value=""></option>
                  <option value="alwar">Alwar</option>
                  <option value="basti">Basti</option>
                  <option value="begusarai">Begusarai</option>
                  <option value="dhanbad">Dhanbad</option>
                  <option value="giridih">Giridih</option>
                  <option value="gaya">Gaya</option>
                  <option value="palamu">Palamu</option>
                  <option value="ramgarh">Ramgarh</option>
                  <option value="santkabirnagar">Santkabirnagar</option>
                  <option value="siddharthnagar">Siddharthnagar</option>
                  <option value="tehri">Tehri</option>  
                  </select>
              </div>
            </div>   
            
            <div class="form-group">
              <label class="col-sm-3 control-label">Block</label>
              <div class="col-sm-7">
                <textarea class="form-control" id="block[]" name="block[]" rows="5" required></textarea>
              </div>
            </div>
            <div class="form-group">
              <label class="col-sm-3 control-label">Sort</label>
              <div class="col-sm-2">
                <input type="text" name="sort" id="sort" class="form-control" />
              </div>
            </div>
            <div class="form-group">
              <label class="col-sm-3 control-label">Status</label>
              <div class="col-sm-2">
                <select class="select2" id="status" name="status" data-placeholder="Status" required>
                  <option value=""></option>
                  <option value="1">Active</option>
                  <option value="0">Inactive</option>
                </select>
              </div>
            </div>   
                    
        <div class="panel-footer">
			 <div class="row">
				<div class="col-sm-6 col-sm-offset-3">
				  <button class="btn btn-primary">Submit</button>&nbsp;
				  <button class="btn btn-default">Cancel</button>
				</div>
			 </div>
		  </div><!-- panel-footer -->
         </form>
      </div><!-- panel -->
