<script type="text/javascript">
	function deletePost(id){
		var iAgree = confirm("You are sure want to delete?.")
		if (iAgree == true){
			document.location.href="<?php echo $this->baseUrl();?>/admin/statecity/delete/id/" + id;
			return(true);
		} else {
			return (false);
		}
	}
</script>

<div class="pageheader">
      <h2><i class="fa fa-home"></i>Manage State,City & Block</h2>
      <div class="breadcrumb-wrapper">
    
        <ol class="breadcrumb">
         
          <li><a href="<?php echo $this->baseUrl();?>/admin/statecity/add"><strong>+ Add</strong></a></li>
        </ol>
      </div>
    </div>
    

<div class="info_container"><span class="info_text">
<?php if(!empty($this->messages[0])){ echo $this->messages[0];}?>
</span></div>   
    

    <div class="contentpanel">
    
     
      <div class="row">
     <div class="col-md-12">
           <table class="table table-success mb30">
                    <thead>
                        <tr>
                            <th width="10">#</th>
                            <th width="200">State</th>
                            <th width="50">City</th>
                            <th width="186">Block</th>
                            <!--<th width="81">Date</th>-->
                            <th width="78">Status</th>
                            <th width="43">Action</th>
                        </tr>
                    </thead>
                    <?php
				  $i = 0;
				  if($this->data){
				  foreach($this->data as $val){
					 	 if($val['status'] == 1){
							$stat =	'<i class="fa fa-check-square-o textgreen" title="Active"></i>'; 
							//$stat = "<img src='".$this->baseUrl()."/public/admin/images/green_icon.png' width='12' height='12' alt='Activated' border='0' title='Activated'/>";
						} else {
							$stat =	'<i class="fa fa-square-o textred" title="Inactive"></i>'; 
							//$stat = "<img src='".$this->baseUrl()."/public/admin/images/red_icon.png' width='12' height='12' alt='Inactivated' border='0' title='Inactivated'/>";
						}
					  ?>
                    <tbody>
                      <tr>
                        <td><?php $i++;echo $i;?>.</td>
                       	<td><?php echo $val['state'];?></td>
                       	<td><?php echo $val['city'];?></td>
                       	<td><?php echo $val['block_name'];?></td>
                       	<!--<td><?php //echo $val['created'];?></td>-->
                       	<td><?php echo $stat;?></td>
                       	<td><!--<a href="#" title="view"><i class="fa fa-search"></i></a>-->
                       	<a href="<?php echo $this->baseUrl();?>/admin/statecity/edit/id/<?php echo $val['location_id'];?>" title="Edit"><i class="fa fa-edit textblue"></i></a>
                       	<a href="javascript:void(0)" onclick="deletePost('<?php echo $val['location_id'];?>')" id="delPost" title="Delete This?"><i class="fa fa-trash-o textred"></i></a>
                       	</td>
                      </tr>
                      <?php } }?> 
                  </tbody>
                </table>
        		<!-- PAGINATION -->
                <table width="100%" border="0" cellspacing="0" cellpadding="0">
                    <tr>
                        <td height="10">
                        <?php 
                        //echo 'I am here ' . count($this->data);
                        //echo $this->pageCount;
                        echo $this->paginationControl($this->data, 'Sliding', 'pagination.phtml');
                        ?>
                        </td>
                    </tr>
                </table>
                <!-- / PAGINATION -->
        
        
        
        
        
        
        
        
        
        
        
        
        

  

                      